language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run lint
before_deploy:
  - npm install now --no-save
deploy:
  provider: script
  script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  domain: todoshque.surge.sh
  project: ./build/
  on:
    branch: master
