language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: todoshque.surge.sh
  project: ./build/
  on:
    branch: master
